fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.25.0"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "4.5.1"
    epel:
      repo: "https://github.com/stahnma/puppet-module-epel.git"
      ref: "1.3.0"
    selinux:
      repo: "https://github.com/voxpupuli/puppet-selinux.git"
      ref: "v1.5.2"
  symlinks:
    varnish: "#{source_dir}"
